# version: '3.8'

services:
  nfl-api:
    build: ./nfl-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  nfl-website:
    build: ./nfl-website
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://nfl-api:5000
    depends_on:
      - nfl-api
    restart: unless-stopped
