# version: '3.8'

services:
  nfl-api:
    build: ./nfl-api
    ports:
      - "5000:5000"
    volumes:
      - ./nfl-api:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  nfl-website:
    build: ./nfl-website
    ports:
      - "8080:80"
    volumes:
      - ./nfl-website:/app
    # Points to the API
    environment:
      - REACT_APP_API_URL=http://3.137.179.246:5000
    depends_on:
      - nfl-api
    restart: unless-stopped
